### ISSUE TITLE
Configuring Firestore

### ISSUE THREAD

**Issue by skskwn** [iiitkottayam/attendance-firebase#5]
Hello
after logging in I only get loading circle.
I referred to 'landing.js' to solve this problem, but I don't understand because I lack coding skills. Could you tell me more about how to add the user collection to FIrestore?

**Comment by shivendra2015iiit** [comment]
You need to configure firebase.
- download the code.
- create firebase app, (follow the instruction there to configure firebase)
- create users collection (see landing.js and make same structure) 
 then you would be able to login, demo app is struck on loading circle because currently there are no users in the configured
database (This project is obsolete for us)

**Comment by skskwn** [comment]
Thank you for your reply. User collection was created and login was successful. But then nothing pops up, the name appears 'null', and the circle rotates indefinitely. How should I modify the document in FIrestore to open the member?

**Comment by shivendra2015iiit** [comment]
@savvysiddharth  or @abhieshekumar  if you can give him a snapshot of DB structure

**Comment by skskwn** [comment]
I'm really sorry, but I don't know how to make the same structure by referring to 'landing.js' in DB. What format should I enter in the DB (refer to landing.js and create the same structure) so that the Attachment App works normally?

**Comment by daemonsloth** [comment]
The attendance structure cannot be observed from firebase console as of now, as it is empty. One has to manage user login to allow logging in as faculty. Then, the db structure will be generated automatically based on scripts.

**Comment by shivendra2015iiit** [comment]
I am closing the issue, this is a POC with lot of non optimize code and DB access.
